### ISSUE TITLE
Support Single Instance Application

### ISSUE THREAD

**Issue by puce77** [Drombler/drombler-fx#102]
For some application there should only be one instance running at one time.

It would be great if DromblerFX could provide such a feature out-of-the-box.

**Comment by puce77** [comment]
Some links:

http://stackoverflow.com/questions/19082265/how-to-ensure-only-one-instance-of-a-java-program-can-be-executed

http://stackoverflow.com/questions/177189/how-to-implement-a-single-instance-java-application

http://stackoverflow.com/questions/10508846/how-to-make-sure-that-only-a-single-instance-of-a-java-application-is-running

https://www.google.ch/?gws_rd=ssl#q=java+application+single+instance

http://stackoverflow.com/questions/920386/how-to-allow-running-only-one-instance-of-a-java-program-at-a-time

**Comment by puce77** [comment]
I think the preferred way would be to use a ServerSocket.
How can we detect if the port is used by another application?

**Comment by SirWindfield** [comment]
A nice feature would be the passing of arguments to the currently running application. If a user or process starts the application for a second instance with some arguments, drombler could just pass them to the currently running instance via a socket.

**Comment by puce77** [comment]
Yes, I'm already working on this. See the branches of this issue and the branches of issue #111 File Type Editor Registration.

Note that most work will be done in the drombler-acp repository as most of this is independent of JavaFX.

https://github.com/Drombler/drombler-acp/blob/102-single-instance/drombler-acp-startup-main/src/main/java/org/drombler/acp/startup/main/impl/singleinstance/SingleInstanceStarter.java

**Comment by SirWindfield** [comment]
Ah ok. Thank you for informing me!

**Comment by puce77** [comment]
See follow-up issue: #153
