### ISSUE TITLE
Maven Build Error

### ISSUE THREAD

**Issue by kugtong33** [Drombler/drombler-fx#104]
Do you have any pre-requisites in building the **drombler-fx** project? and if there are, would you mind posting it here in **github**?

```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.drombler:drombler-oss-parent:2.2-SNAPSHOT: Could not find artifact org.softsmithy:softsmithy-parent:pom:2.7-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 18, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.drombler:drombler-oss-parent:2.2-SNAPSHOT (/github/drombler-oss-parent/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.drombler:drombler-oss-parent:2.2-SNAPSHOT: Could not find artifact org.softsmithy:softsmithy-parent:pom:2.7-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 18, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

The problem is about `org.softsmithy:softsmithy-parent:pom:2.7-SNAPSHOT`

**Comment by puce77** [comment]
Yes, the SoftSmithy Parent POM is another project of mine, where I define common pluginManagement etc.

https://github.com/SoftSmithy/softsmithy-parent

I guess I shouldn't have merged a SNAPSHOT-dependency, though. Thanks for pointing this out!

I just released v2.7 of the SoftSmithy Parent and will update the Drombler OSS Parent once it becomes available in Maven Central.

**Comment by puce77** [comment]
To build Drombler FX, you'll likely will also have to build the following Drombler projects:

https://github.com/Drombler/drombler-oss-parent

https://github.com/Drombler/drombler-commons

https://github.com/Drombler/drombler-acp

Or define a proxy to the following repository in your Maven Repository Manager (eg. Nexus): https://oss.sonatype.org/content/repositories/snapshots/

See also: http://www.drombler.org/drombler-fx/

**Comment by puce77** [comment]
drombler-oss-parent is now updated on the develop branch
