### ISSUE TITLE
Provide example of modular FX application

### ISSUE THREAD

**Issue by HighTower1991** [Drombler/drombler-fx#110]
1. How I should used drombler and OSGi in JavaFX? Could you, please, write some example application with two modules?
2. What features are offered by drombler-fx additionaly compared of OSGi implementation, for example Apache Felix?
3. Weld as CDI implementatioon are supported OSGi runtime. May I use Weld with Drombler-fx?

**Comment by puce77** [comment]
For point 1. and 2. please have a look at the tutorial (http://www.drombler.org/drombler-fx/current/docs/tutorial) and especially at the Getting Started page and the sample application (http://www.drombler.org/drombler-fx/current/docs/tutorial/getting-started.html#gettingStarted)

For point 3, please join the discussion at: https://github.com/Drombler/drombler-fx/issues/38
