### ISSUE TITLE
Spilt pane divider bug

### ISSUE THREAD

**Issue by SirWindfield** [Drombler/drombler-fx#115]
If you move the split pane divider that is used between the left and the center elements in a test application generated by ```mvn archetype:generate -DarchetypeGroupId=org.drombler.fx -DarchetypeArtifactId=drombler-fx-maven-archetype-application -DarchetypeVersion=0.7 -DgroupId=com.mycompany.test -DartifactId=test -Dversion=0.1-SNAPSHOT -DbrandingId=foo```, both dividers, the one that splits the top and the center view and the one that is in between the bottom and the center view, move to the edge of the application on OS X. [Here](https://youtu.be/_2nl1BuRoAg) is a youtube video show casing the bug.

**Comment by puce77** [comment]
Duplicate of #46
(see comments)

**Comment by SirWindfield** [comment]
Haha sorry, missed that!
