### ISSUE TITLE
Configuration file for application missing

### ISSUE THREAD

**Issue by SirWindfield** [Drombler/drombler-fx#117]
I can't find the configuration file that lets you the title, width, height, application icon etc. Maven doesn't generate any config files in the bin folder.

**Comment by puce77** [comment]
The applicationConfig.properties file is packaged with the main jar (bin folder) in the default package (root), as this configuration should not be changed by the user.

**Comment by puce77** [comment]
Closing this issues as answered. Feel free to re-open it, if you need more information.

**Comment by SirWindfield** [comment]
Just found that you can change those values in the pom.xml file. I feel stupid :(
