### ISSUE TITLE
Make HostServices available to bundles

### ISSUE THREAD

**Issue by puce77** [Drombler/drombler-fx#121]
Currently it's not possible to access HostServices from a bundle.

Make the HostServices available to bundles, e.g. by registering them as an OSGi service.

**Comment by SirWindfield** [comment]
Simply calling `FrameworkUtil.getBundle(getClass()).getBundleContext().registerService(HostServices.class.getName(), getHostServices());` in the application class should be enough.

**Comment by puce77** [comment]
Almost. We use the Framework BundleContext here, as this is in the start-up code.
You can see the related pull request here: https://github.com/Drombler/drombler-fx/pull/124/files
