### ISSUE TITLE
[Feature] Provide primaryStage that holds the main window

### ISSUE THREAD

**Issue by SirWindfield** [Drombler/drombler-fx#122]
This can be useful if the application wants to display dialogs on top of the main window. Setting the primaryStage as the parent of a dialog will prevent users from switching focus.

**Comment by puce77** [comment]
I guess you're looking for [MainWindowProvider](http://www.drombler.org/drombler-acp/0.7/docs/site/apidocs/org/drombler/acp/startup/main/MainWindowProvider.html).

Feel free to re-open this issue again, if you think this doesn't solve the issue.

**Comment by SirWindfield** [comment]
Ye, sorry. Looks like I missed this one. I was looking into the drombler-fx-core bundle.
