### ISSUE TITLE
Gitter.im Room?

### ISSUE THREAD

**Issue by SirWindfield** [Drombler/drombler-fx#131]
I just wanted to mention [Gitter.im](https://gitter.im/), a platform where developer (and users) can discuss new ideas, bugs and maybe just exchange ideas about projects. People can login using there Github account and then create a room for a repository. That room can then be used to chat with people (Instant Messaging). It is not optimal for bug reports and issues but can be used to ask small questions concerning some usage of some API or maybe asking why you implemented x in that way and not another. 

I personally use it for my applications so people can come and ask questions on how to use feature x and feature y or why feature z is disabled etc. 
I know that questions can be ask on stackoverflow but not all of them are worth a question on SO. Adding a link to Gitter.im in the README.MD of drombler could also be done.

Just a small die :smile:

**Comment by puce77** [comment]
I'm not familiar with Gitter, but we I'm open to try it out. I also haven't compared it much yet to other solutions, but let's start with Gitter now and change later if there is a good reason.

**Comment by puce77** [comment]
I've creatd a Gitter room here: https://gitter.im/Drombler/drombler-fx

**Comment by puce77** [comment]
I've added a link on the GitHub page: http://www.drombler.org/drombler-fx/
