### ISSUE TITLE
Userdir not working as expected

### ISSUE THREAD

**Issue by claudio-rosati** [Drombler/drombler-fx#173]
Following the Getting Started version 0.9.

1.  When I run the sample application using the `java -Duser.language...` command I'm expecting to find the cache folder inside `test-application/target/userdir`. Instead it is inside `test-application/target/userdir/target/userdir`.

1. When I run the sample application using the java `-Duser.language...` command without the `--userdir target/userdir` option, the following directory is created inside `test-application`: `{user.home}/.foo/1.0.0-SNAPSHOT/{user.home}/.foo/1.0.0-SNAPSHOT`. Inside it the cache folder can be found.

1. When I run the application double-clicking `foo.jar`, inside `test-application/target/deployment/standalone/bin` the following directory is created: `{user.home}/.foo/1.0.0-SNAPSHOT/{user.home}/.foo/1.0.0-SNAPSHOT`. Inside it the cache folder can be found.

**Configuration:**
- OS: MacOS X 10.12.3 
- Java: 1.8.0_121 
- Maven: 3.3.9 
- Env Vars: JAVA_HOME, M2_HOME and M2 are set.
- NetBeans 8.2 IDE (where the maven project is loaded and executed from the inner console).

**Comment by claudio-rosati** [comment]
For what concerns point 3, I've changed the content of `test-application/target/deployment/standalone/conf/config.properties` from

```
#
#Thu Mar 09 14:52:37 CET 2017
platform.userdir=${dollar}{user.home}/.foo/1.0.0-SNAPSHOT
```

to

```
#
#Thu Mar 09 14:52:37 CET 2017
platform.userdir=${user.home}/.foo/1.0.0-SNAPSHOT
```

(i.e. removing the `{dollar}` part) and the application now started correcty creating the `.foo/1.0.0-SNAPSHOT/cache` folder inside my home directory.

**Comment by puce77** [comment]
Together with https://github.com/Drombler/drombler-acp/pull/48/files this issue should be fixed.

**Comment by puce77** [comment]
And this PR: https://github.com/Drombler/drombler-oss-parent/pull/8/files

**Comment by puce77** [comment]
Make sure you have the following property in your dromblerfx-application POM, if you don't inherit from drombler-oss-parent.

`<dollar>$</dollar>  `

**Comment by claudio-rosati** [comment]
I've added `<dollar>$</dollar>` to the application properties and reset the content of `test-application/target/deployment/standalone/conf/config.properties` and now it works well.
Thank you
