### ISSUE TITLE
Docking frameword D&D

### ISSUE THREAD

**Issue by claudio-rosati** [Drombler/drombler-fx#174]
Do you plan to included D&D capabilities do the docking framework?
Something like [AnchorFX](https://github.com/alexbodogit/AnchorFX)?

**Comment by puce77** [comment]
Yes, this is on our feature list: https://github.com/Drombler/drombler-fx/labels/Docking%20Framework

Please note that there is an open JavaFX issue, which prevents a clean solution: https://bugs.openjdk.java.net/browse/JDK-8092098

**Comment by claudio-rosati** [comment]
OK, thank you
