### ISSUE TITLE
File extension used in AbstractDocumentHandler

### ISSUE THREAD

**Issue by claudio-rosati** [Drombler/drombler-fx#176]
Hello,

in the sample application, then FooHandler uses a file extension set to `"foo"`.

On my mac, when I select `Fille > Open` ony files named `"foo"` can be selected when the filter is `Foo Document [foo]`.

To open file whose extension is .foo I have to use `"*.foo"` instead (displayed as `Foo Document [*.foo]` filter in the open dialog).

I don't understand if this is a bug or not. In the last case maybe a short description should be provided in the tutorial.

Anyway, once the file is correctly selected, no editor is displayed, no error messages in console.

**Configuration:**
- OS: MacOS X 10.12.3
- Java: 1.8.0_121
- Maven: 3.3.9
- Env Vars: JAVA_HOME, M2_HOME and M2 are set.
- NetBeans 8.2 IDE (where the maven project is loaded and executed from the inner console).

**Comment by puce77** [comment]
I have to investigate this and will come back to you.

**Comment by puce77** [comment]
On Linux, everything works as expected (*.foo are shown and can be loaded).
I will check it on a Mac as well.

**Comment by puce77** [comment]
The class which manages the FileChooser:  drombler-fx/drombler-fx-core-data/src/main/java/org/drombler/fx/core/data/impl/FXFileChooserProvider.java

**Comment by claudio-rosati** [comment]
Hello @puce77,

I've done some tests (see [file-chooser-test.zip](https://github.com/Drombler/drombler-fx/files/857894/file-chooser-test.zip)) to understand how the filter mus be built to work on the various platforms. With the test application one should be able to select a `sample.foo` file somewere in the disk.

I've installed 4 filters:

- "foo"
- ".foo"
- "*foo"
- "*.foo"

The results are the following:

- "*foo" works both on Windows 7 and Linux (I'm using CentOS 7.1 for the test);
- "*.foo works on MacOS X, WIndows 7 and Linux.

On MacOS X "*foo" will selects files without extensions whose name ends in '*foo".

That said, my proposal is to change line 88 of FXFileChooserProvider.java to the following:

`.map(fileExtension -> WILDCARD + "." + fileExtension.toLowerCase())`

(Or include '.' inside WILDCARD).
