### ISSUE TITLE
What to do when a new versions is released

### ISSUE THREAD

**Issue by claudio-rosati** [Drombler/drombler-fx#177]
I'm about to start a project development based on drombler-fx.
Currently I've followed the sample example provided wit rel. 0.9.
I wander what I have to do to my project when a new version of drombler-fx is releases (I mean what files I have to modify, what kind of modification are needed...). 
Can this information be added to the documentation pages?

**Comment by puce77** [comment]
I write a blog entry for every new release here: http://puces-blog.blogspot.ch/search/label/Drombler

I will see if I can provide more information in the future.

**Comment by claudio-rosati** [comment]
What I mean is the following: in the pom file under the -parent module there is the following:

```xml
    <properties>
        <drombler-fx.version>0.9</drombler-fx.version>
    </properties>
```

Changing it from 0.9 to tne new version and rebuilding the wole project is enough to have the new version of jar files being deployed with my application?

**Comment by puce77** [comment]
Yes, you need to update the version of Drombler FX, which by default can be controlled by the mentioned property. Please note that in some releases there might be some backwards incompatible changes. Please have a look at my blog posts and also check the newest version of the sample project, if you have any issues during an update, as the sample application covers most features.

**Comment by claudio-rosati** [comment]
thank  you
