### ISSUE TITLE
Continous Integration

### ISSUE THREAD

**Issue by kugtong33** [Drombler/drombler-fx#90]
We would create a `.travis.yml` file for the scripts necessary in automating tests in every commit or merge. The document is [here](http://docs.travis-ci.com/user/languages/java/). There is also a logo for build status to determine bugs and code feedback faster like this:

![Build Status](https://travis-ci.org/Lintad/fxQuery.svg)

I will check the project later this week and see what I can help.

**Comment by puce77** [comment]
Have you seen the .travis.yml file in the develop branch? There are still some issues however.

https://travis-ci.org/Drombler/drombler-oss-parent
https://travis-ci.org/Drombler/drombler-commons
https://travis-ci.org/Drombler/drombler-acp
https://travis-ci.org/Drombler/drombler-fx

I also have a local Jenkins running. The builds are running fine there.

**Comment by kugtong33** [comment]
Why are you always ahead of time? :D I only looked the `master` branch, might be the time to merge now? I think it is better to only have a `master` branch in the main repository to avoid confusion among new developers who wants to help.

I would rather prefer `master` as the `development` branch than to have a separate `develop` branch for faster development, There are already tags for stable releases and `travis-ci` for build state no need to have a separate `develop` branch where rapid development is happening. If you insist on using a separate branch try using `feature` branches instead rather than a generic `develop` branch.

Might be the right time also to document on how to contribute on this project using `CONTRIBUTING.md` so that others can also have an idea where to start and to avoid redundant issues like this one? Or you can directly tell me on what issues should I focus because there is a lot of issues that you created. I can can also directly do these things instead of just doing speeches but you might kill me because it might disrupt your own flow of development.

**Comment by puce77** [comment]
I'm trying to setup what is known as "Git-Flow": http://nvie.com/posts/a-successful-git-branching-model/

I'm not there yet, but the goal is:

- master: only contains released code. develop gets merged to master during releasing.
- develop: only contains released code and finished features of the current sprint
- feature/xyz: feature branches, usually only available in forks and can be merged to develop with a pull request.

I'll document how to contribute but unfortunately I need to solve some legal issues first.

Bear with me.

**Comment by puce77** [comment]
From your comment I get that this issue can be closed.

**Comment by kugtong33** [comment]
I already read the article a year ago, and the idea is a little bit outdated but still a great help with those still starting to use git in a large team or in an organization. Using the `master` branch as the `development` branch is not a matter of **git** context but a matter of **github** context (as I stated, **github** uses the `master` branch as the default branch shown in the repository). When someone visits the repository he sees the `master` branch automatically which is a bit low in commit activity (because we can see the date of the last commit in the repository). The default `README.md` file shown is the one in the `master` branch so I would not know that the development is active unless I select the `develop` branch that a browsing user would definitely not do.

I am sorry if I am a bit impatient. :D

**Comment by puce77** [comment]
I thought about this as well. I first thought that it's better for people to see the most stable branch, but maybe you're right and it's better to see the branch where the development is happening.

So I changed the default branch from master to develop. Does this solve (most) of your points?

**Comment by kugtong33** [comment]
Yes, showing the rapid development side is like marketing your project and encourage others to take a look, or giving them the confidence to use this framework because it is **active**.

**Comment by puce77** [comment]
Thanks for your feedback.
